CREATE TABLE IF NOT EXISTS wrong_question_notebook (
  id                    BIGINT       NOT NULL AUTO_INCREMENT,
  student_no            VARCHAR(64)  NOT NULL           COMMENT 'Primary key - matches StudentSessionResolver.requireStudentId() canonical student number',
  problem_id            BIGINT       NOT NULL           COMMENT 'FK -> leetcode_problem_bank.id',
  problem_title         VARCHAR(512) NOT NULL           COMMENT 'Denormalized for display',
  problem_slug          VARCHAR(255) NULL,
  difficulty            VARCHAR(16)  NULL,
  source_type           VARCHAR(24)  NOT NULL           COMMENT 'LEETCODE_PRACTICE / PTA_SYNCED',
  first_wrong_at        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  last_wrong_at         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  total_wrong_count     INT          NOT NULL DEFAULT 0,
  consecutive_ac_count  INT          NOT NULL DEFAULT 0  COMMENT 'Reset to 0 on any non-AC; >= 2 marks resolved',
  last_attempt_at       TIMESTAMP(3) NULL,
  last_judge_status     VARCHAR(64)  NULL,
  last_wrong_code       MEDIUMTEXT   NULL                COMMENT 'Last failed submission source code',
  last_error_message    TEXT         NULL,
  error_category        VARCHAR(32)  NULL                COMMENT 'WRONG_ANSWER / COMPILE_ERROR / RUNTIME_ERROR / TIME_LIMIT_EXCEEDED / MEMORY_LIMIT_EXCEEDED / UNKNOWN',
  is_resolved           TINYINT(1)   NOT NULL DEFAULT 0,
  resolved_at           TIMESTAMP(3) NULL,
  tags_cached           VARCHAR(512) NULL                COMMENT 'Comma-separated tags consumed by recommendation service',
  notes                 TEXT         NULL                COMMENT 'Private student notes',
  created_at            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_wrong_question_per_source (student_no, problem_id, source_type),
  KEY idx_wrong_q_student_resolved   (student_no, is_resolved),
  KEY idx_wrong_q_student_last_wrong (student_no, last_wrong_at),
  KEY idx_wrong_q_student_source     (student_no, source_type),
  CONSTRAINT fk_wrong_q_problem FOREIGN KEY (problem_id) REFERENCES leetcode_problem_bank(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Wrong-answer notebook - one row per (student, problem, source) triple';

CREATE TABLE IF NOT EXISTS wrong_question_attempt_log (
  id              BIGINT       NOT NULL AUTO_INCREMENT,
  notebook_id     BIGINT       NOT NULL,
  attempt_at      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  judge_status    VARCHAR(64)  NOT NULL,
  was_ac          TINYINT(1)   NOT NULL,
  code_snippet    MEDIUMTEXT   NULL,
  runtime_ms      INT          NULL,
  memory_kb       INT          NULL,
  source          VARCHAR(24)  NOT NULL   COMMENT 'NOTEBOOK_PRACTICE / EXTERNAL_PRACTICE',
  created_at      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_wrong_qlog_notebook_time (notebook_id, attempt_at),
  CONSTRAINT fk_wrong_qlog_notebook FOREIGN KEY (notebook_id) REFERENCES wrong_question_notebook(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Per-attempt detail log for wrong-question notebook';
